name: Trend
description: Music videos over and over.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: 
  ext_video_player: ^0.0.3
  assets_audio_player: 2.0.8+3 
  rate_my_app: ^0.7.2
  flutter_auth_buttons: ^0.8.0
  google_sign_in:
  flutter_email_sender: ^3.0.1
  keyboard_avoider: ^0.1.2
  http: ^0.12.2
  custom_switch: ^0.0.1
  animations: ^1.1.2
  flutter_radio: ^0.1.8
  get: ^3.10.1
  timer_builder: ^1.3.0
  splashscreen: ^1.2.0
  cupertino_icons: ^0.1.3
  flutter_webview_plugin: ^0.3.10+1
  firebase_auth: 
  firebase_core: 
  firebase_database: 
  cloud_firestore: ^0.14.4
  lottie: ^0.6.0
  animated_splash_screen: ^1.0.1+2
  get_storage: ^1.3.1
  flutter_spinkit: ^4.1.2
  cached_network_image:
  webview_flutter_plus: ^0.1.1+9

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/videos/login_video_animation.mp4
    - assets/images/dj_features.jpg
    - assets/images/documentaries.png
    - assets/images/propose.jpg
    - assets/images/hard.jpg
    - assets/images/body.jpg
    - assets/images/background.png
    - assets/images/intimidated.jpg
    - assets/images/screen_example.jpg
    - assets/images/listen_mic.png
    - assets/images/shadow.png
    - assets/images/mampi.jpg
    - assets/images/mampi2.jpg
    - assets/images/girl1.jpg
    - assets/images/background_fade.png
    - assets/images/play.png
    - assets/images/play_small.png
    - assets/logo/logo.png
    - assets/logo/logo_white.png
    - assets/images/overlay.png
    - assets/images/play_cover.png
    - assets/images/leading.png
    - assets/json/Trend-Splash-Animation.json
    - assets/terms/termsofuse.txt
    - assets/images/TV_SCREEN/

  fonts:
      - family: Sofia_regular
        fonts:
          - asset: assets/fonts/sofia_regular.ttf
      - family: Sofia_bold
        fonts:
        - asset: assets/fonts/sofia_bold.ttf
      - family:  TrendIcons   
        fonts:
          - asset: assets/fonts/TrendIcons.ttf

  # adaptive_icon_background: “lib/assets/launcher/background.png”
  # adaptive_icon_foreground: “lib/assets/launcher/foreground.png”
  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
